HyperV2012r2_VHDX:
  test_suite: default
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhdx.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
HyperV2012r2_VHDX_fixed:
  test_suite: images
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64-fixed.vhdx.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
HyperV2012r2_VHDX_no_CoW:
  test_suite: default
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhdx.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          use_cow_images: false
          allow_resize_to_same_host: false
          debug: true
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          use_cow_images: false
          allow_resize_to_same_host: false
          debug: true
HyperV2012r2_VHDX_fixed_no_CoW:
  test_suite: images
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64-fixed.vhdx.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          use_cow_images: false
          allow_resize_to_same_host: false
          debug: true
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          use_cow_images: false
          allow_resize_to_same_host: false
          debug: true
HyperV2012r2_VHD:
  test_suite: default
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhd.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
HyperV2012r2_VHD_fixed:
  test_suite: images
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64-fixed.vhd.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
HyperV2012r2_dynamic_memory:
  test_suite: default
  devstack:
    live_migration: true
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhdx.gz
  hosts:
    NUCHV12R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
        hyperv:
          dynamic_memory_ratio: 1.5
    NUCHV12R202:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
        hyperv:
          dynamic_memory_ratio: 1.5
HyperV2012_VHDX:
  test_suite: default
  devstack:
    live_migration: false
    allow_resize_to_same_host: true
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhdx.gz
  hosts:
    NUCHV1201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: true
          debug: true
HyperV2012_VHD_v1:
  test_suite: default
  devstack:
    live_migration: false
    allow_resize_to_same_host: true
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhd.gz
  hosts:
    NUCHV1201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: true
          debug: true
        hyperv:
          force_hyperv_utils_v1: true
          force_volumeutils_v1: true
HyperV2008r2:
  test_suite: default
  devstack:
    live_migration: false
    allow_resize_to_same_host: true
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhd.gz
  hosts:
    NUCHV08R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: true
          debug: true
