HyperV2012r2_VHDX:
  test_suite: default
  devstack:
    live_migration: false
    allow_resize_to_same_host: false
    image_url: https://raw.githubusercontent.com/cloudbase/ci-overcloud-init-scripts/master/scripts/devstack_vm/cirros-0.3.3-x86_64.vhdx.gz
    heat_image_url: https://www.cloudbase.it/downloads/Fedora-x86_64-20-20140618-sda.vhdx.gz
  hosts:
    HV12R201:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
          instances_path: 'Z:'
          compute_driver: hyperv.nova.cluster.driver.HyperVClusterDriver
      neutron_hyperv_agent.conf:
        DEFAULT:
          debug: true
        SECURITYGROUP:
          enable_security_group: true
    HV12R202:
      nova.conf:
        DEFAULT:
          allow_resize_to_same_host: false
          debug: true
          instances_path: 'Z:'
          compute_driver: hyperv.nova.cluster.driver.HyperVClusterDriver
      neutron_hyperv_agent.conf:
        DEFAULT:
          debug: true
        SECURITYGROUP:
          enable_security_group: true
